config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  post '/search' => 'application#search'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :categories, except: :destroy do
    member do
      post 'sub'
      post 'unsub'
    end

    resources :questions, only: [:create, :show, :index], shallow: true do
      post 'vote', on: :member

      resources :comments, only: [:create] do
        member do
          post 'vote'
          post 'best_answer'
        end
      end
    end
  end

  get '/register' => 'users#new'
  resources :users, except: [:destroy] do

    member do
      resources :messages, only: [:new, :create]
      get 'avatar'
      patch 'update_avatar'
      delete 'delete_avatar'
    end
  end

  resources :email_verifications, only: :edit

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/question.rb
class Question < ActiveRecord::Base
  PER_PAGE = 6

  include Searchable
  include Voteable

  default_scope {order('created_at ASC')}

  belongs_to :category
  belongs_to :creator, foreign_key: :user_id, class_name: :User
  has_many :comments
  has_many :votes, as: :voteable

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_user, only: [:create, :vote]
  before_action :find_question, only: [:show, :vote, :answered]
  before_action :require_verified, only: [:create]

  def index
    if logged_in?
      count ||= 0
      ids ||= current_user.subs.ids
      count += Question.where(category_id: ids).size
      @questions = Question.where(category_id: ids).limit(Question::PER_PAGE).offset(params[:offset]).sort_by{|x| x.vote_count}.reverse
      @pages = (count.to_f / Question::PER_PAGE).ceil
    else
      @pages = (Question.all.size.to_f / Question::PER_PAGE).ceil
      @questions = Question.limit(Question::PER_PAGE).offset(params[:offset]).sort_by{|x| x.vote_count}.reverse
    end
  end

  def show
    @comment = Comment.new

    @comments = @question.comments.limit(Comment::PER_PAGE).offset(params[:offset]).sort_by{|x| x.vote_count}.reverse
    @pages = (@question.comments.size.to_f / Comment::PER_PAGE).ceil
  end

  def create
    @category = Category.find(params[:category_id])
    @question = @category.questions.new(question_params)
    @question.creator = current_user

    respond_to do |format|
      format.html do
        if @question.save
          flash[:success] = "Your question has been created"
          redirect_to @question.category
        else
          render 'categories/show'
        end
      end

      format.js {render layout: false}
    end
  end

  def vote
    vote = Vote.new(voteable: @question, creator: current_user, vote: params[:vote])

    if vote.valid?
      if @question.check_vote(current_user).nil?
        vote.save
        @question.counter(params[:vote])
      else
        @question.change_vote(params[:vote])
      end
    end

    respond_to do |format|
      format.html do
        flash[:error] = "You can't Vote on your own question" if !vote.valid?
        redirect_to :back
      end

      format.json {render json: [@question, vote]}
    end
  end

private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/views/questions/_form.slim
= form_for [@category, @question], remote: true do |f|
  .row
    .input-field.col.s12
      = f.text_field :title
      = f.label :title, 'Question', for: 'title'

  .row
    .input-field.col.s12
      = f.text_area :body
      = f.label :body, 'Further details', for: 'body'

  .row
    .input-field.col.s12
      = f.button :submit, class: 'btn waves-effect waves-light' do
        = content_tag(:span, "Submit")

app/views/questions/_question.slim
- if question.valid?
  .card-panel.grey.lighten-5.z-depth-1
    .row
      .valign-wrapper
        .col.s2.center-align.valign
          - if logged_in?
            = render 'shared/vote', obj: question, url: vote_question_path(question)
          -else
            br
              strong= question.vote_count

          small
            = link_to question do
              = pluralize question.comments.count, 'Comment'
          small.text-muted.hide-on-small-only
            '  | Asked
            = time_ago_in_words question.created_at
            '  ago

        .col.s10.m8
          = link_to question.title, question_path(question)
          = link_to question.category.name, question.category, class: "right"
          h6.truncate
            = question.body

        .col.s2.right-align.hide-on-small-only
          = link_to question.creator do
            = image_tag question.creator.avatar_url, class: 'responsive-img avatar'
            br
            = question.creator.username


      .answered-question
        - if question.answered
          i.answered<

app/views/questions/create.js.slim
-if @question.save
  | var questions = $("#category-questions");
    var newQuestion = $(".new-question");
    if (questions.find(".contain:first-child").hasClass("align")) {
      questions.prepend("#{j render(@question)}");
      questions.find(".contain:first-child").removeClass("hld").addClass("align").css('border-left', '4px solid #88929d');
    } else {
      questions.prepend("#{j render(@question)}");
      questions.find(".contain:first-child").css('border-left', '4px solid #88929d');
    }
    newQuestion.find(".field_with_errors").removeClass('field_with_errors');
    newQuestion.find(".alert-danger").remove();
    newQuestion.find('.form-control').val('');
-else
  | $(".new-question").replaceWith("#{j render 'questions/form'}");

app/views/questions/index.slim
= render 'shared/header', title: 'All questions'

= render @questions
- if @questions.empty?
  .card-panel.orange.darken-4.z-depth-3
      | You don't have any subscriptions yet! Now that you're logged in click over to categories or enter a search term.
          All questions for your category subscriptions will be found here.


- if @questions.any?
  .col.s12
    = render 'shared/pagination', page_count: Question::PER_PAGE, url: root_path

app/views/questions/show.slim
=render @question

aside#comment
  =render 'categories/subscribe', category: @question.category
  -if logged_in?
    =render 'comments/form'



#question-comments
  -if @question.comments.any?
    h4.text-center Comments
  -else
    h4.text-center No Comments
  =render @comments

  =render 'shared/pagination', page_count: Comment::PER_PAGE, url: question_path(@question)