config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  post '/search' => 'application#search'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :categories, except: :destroy do
    member do
      post 'sub'
      post 'unsub'
    end

    resources :questions, only: [:create, :show, :index], shallow: true do
      post 'vote', on: :member

      resources :comments, only: [:create] do
        member do
          post 'vote'
          post 'best_answer'
        end
      end
    end
  end

  get '/register' => 'users#new'
  resources :users, except: [:destroy] do

    member do
      resources :messages, only: [:new, :create]
      get 'avatar'
      patch 'update_avatar'
      delete 'delete_avatar'
    end
  end

  resources :email_verifications, only: :edit

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :verification_token, :reset_token

  before_save :downcase_email
  before_save :set_avatar
  before_create :create_verification_digest
  before_create :set_default_subs

  validates :username, presence: true, length: {in: 3..50}, uniqueness:
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                              format: {with: EMAIL_REGEX},
                      uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, length: {minimum: 5}, allow_blank: true

  has_many :comments
  has_many :questions

  has_many :user_categories
  has_many :subs, through: :user_categories, source: :category

  has_many :recieved_messages, class_name: :Message, foreign_key: :recipient_id
  has_many :sent_messages, class_name: :Message, foreign_key: :sender_id

  has_many :unread_messages, -> (obj) {where('read is false')}, class_name: :Message, foreign_key: :recipient_id

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update(remember_digest: User.digest(remember_token))
  end

  def forget
    update(remember_digest: nil)
    @current_user = nil
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def verify
    update(verified: true)
    update(verified_at: Time.zone.now)
  end

  def send_verification_email
    UserMailer.email_verification(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update(reset_digest: User.digest(reset_token))
    update(reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def mark_unread_messages!
    unread_messages.each do |msg|
      msg.mark_read!
    end

    self.unread_messages.clear
  end

  def delete_avatar
    key = self.avatar_url.match(/[^"]+/, 35).to_s
    unless key.empty? || self.avatar_url.include?('avatar-placeholder.png')
      obj = S3_BUCKET.object(key)
      obj.delete if obj.exists?
    end
  end

  def set_avatar
    self.avatar_url = 'https://s3.amazonaws.com/diyavatar/avatar-placeholder.png' if self.avatar_url.blank?
  end

private

  def set_default_subs
    self.subs << Category.where(id: [1, 2, 3])
  end

  def downcase_email
    self.email = email.downcase
  end

  def create_verification_digest
    self.verification_token = User.new_token
    self.verification_digest = User.digest(verification_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :avatar, :update_avatar, :delete_avatar]
  before_action :require_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :user_activity, only: :show
  after_action :uploads_cleaner, only: :update_avatar

  def show
    @show_msgs = true if @user == current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      flash[:success] = 'Your profile has been created'
      @user.send_verification_email
      log_in @user
      store_user
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      store_user
      flash[:success] = 'Your profile has been updated.'
      redirect_to @user
    else
      render :edit
    end
  end

  def avatar
    @s3_bucket = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}-${filename}",
                                          success_action_status: "201",
                                          acl: "public-read-write")
  end

  def update_avatar
    if params[:user] && params[:user][:avatar_url].include?('https://diyavatar')
      @user.delete_avatar
      @user.update(avatar_url: params[:user][:avatar_url])

      flash[:success] = 'Your avatar has been updated.'
      redirect_to @user
    else
      flash.now[:error] = 'Sorry there was an issue uploading your image. Please try again.'
      render :avatar
    end
  end

  def delete_avatar
    @user.delete_avatar
    @user.update(avatar_url: nil)
    redirect_to @user
  end

private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar_url)
  end

  def uploads_cleaner
    extras = params[:uploads].split
    extras.each do |key|
      S3_BUCKET.objects[key].delete if @user.avatar_url.match(/[^"]+/, 35).to_s != key
    end
  end

  def find_user
    @user = User.find params[:id]
  end

  def store_user
    params[:remember_me].nil? ? forget(@user) : remember(@user)
  end

  def user_activity
    case params[:tab]
      when "comments"
        @activity = Comment.where(creator: @user).limit(Comment::PER_PAGE).offset(params[:offset])
        @pages = (@user.comments.size.to_f / Comment::PER_PAGE).ceil
      when "recieved"
        @activity = Message.where(recipient_id: @user.id).limit(Message::PER_PAGE).offset(params[:offset])
        @pages = (@user.recieved_messages.size.to_f / Message::PER_PAGE).ceil
      when "sent"
        @activity = Message.where(sender_id: @user.id).limit(Message::PER_PAGE).offset(params[:offset])
        @pages = (@user.sent_messages.size.to_f / Message::PER_PAGE).ceil
      when nil
        @activity = Question.where(user_id: @user.id).limit(Question::PER_PAGE).offset(params[:offset])
        @pages = (@user.questions.size.to_f / Question::PER_PAGE).ceil
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !!current_user
  end

  def require_verified
    unless current_user.verified
      flash[:error] = 'Please verify your email to do that.'
      redirect_to :back
    end
  end
end

app/views/users/_avatar.erb
<script>
  $(function() {
    $('.directUpload').find("input:file").each(function(i, elem) {
      var fileInput = $(elem);
      var uploadBtn = $('.btn-success');
      var updateBtn = $('.btn-primary');
      var form = $(fileInput.parents('form:first'));
      var progressBar = $("<div class='status active'></div>");
      var barContainer = $("<div class='progress'></div>").append(progressBar);
      $('#avatar-form').before(barContainer);
      fileInput.fileupload({
        fileInput: fileInput,
        url: '<%= @s3_bucket.url %>',
        type: 'POST',
        autoUpload: false,
        formData: <%= @s3_bucket.fields.to_json.html_safe %>,
        paramName: 'file',
        dataType: 'XML',
        disableImageResize: /Android(?!.*Chrome)|Opera/
          .test(window.navigator && navigator.userAgent),
          imageMaxWidth: 300,
          imageMaxHeight: 400
        }).on('fileuploadadd', function(e, data){
          uploadBtn.click(function(){
            data.submit()
          });
        }).on('fileuploadprogressall', function(e, data){
          var progress = parseInt(data.loaded / data.total * 100, 10);
          progressBar.css('width', progress + '%')
        }).on('fileuploadstart', function(e, data){
          $('.btn-success').prop('disabled', true);
          progressBar
          .css('width', '0%')
          .text('Loading...');
        }).on('fileuploaddone', function(e, data){
          $('.btn-success').prop('disabled', false);
          progressBar.text('Uploading done');
          var key = $(data.jqXHR.responseXML).find("Key").text();
          var url = '<%= @s3_bucket.url %>' + key;
          var input = $("<input />", {type:'hidden', name: fileInput.attr('name'), value: url});
          form.append(input);
          var uploads = $('#uploads').val();
          $('#uploads').val(uploads + key + ' ');
        }).on('fileuploadfail', function(e, data){
          $('.btn-success').prop('disabled', false);
          progressBar
          .css('background', 'red')
          .text('Failed')
        });
      });
      document.getElementById('avatar').onchange = function(e) {
        loadImage(
          e.target.files[0],
          function(img) {
            var scaledImage = loadImage.scale(
              img,
              {maxWidth: 300},
              {maxHeight: 400}
            );
            $('canvas').replaceWith(scaledImage);
          },
          {canvas: true}
        );
      };
      var imageObj = new Image();
      imageObj.src = '<%= @user.avatar_url %>'
      if (imageObj.src.match(/\/avatar-placeholder.png/)) {
        imageObj.src = 'https://s3.amazonaws.com/diyavatar/avatar.png'
      }
      imageObj.onload = function() {
        var canvas = document.getElementById('myCanvas')
        var context = canvas.getContext('2d');
        var width = imageObj.width
        var height = imageObj.height
        context.drawImage(imageObj, (canvas.width - width) / 2, (canvas.height - height) / 2, width, height);
      }
    });
</script>

app/views/users/_form.slim
- new_user = @user.new_record?
= render 'shared/header', title: new_user ? 'Register' : 'Edit Profile'

= form_for @user do |f|
  .row
    .input-field.col.s12
      = f.text_field :username, id: 'username'
      = f.label :username, for: 'username'

  .row
    .input-field.col.s12
      =f.email_field :email, class: 'validate', id: 'email'
      =f.label :email, for: 'email'

  .row
    .input-field.col.s12
      =f.password_field :password, id: 'password'
      =f.label :password, for: 'password'

  .row
    .input-field.col.s12
      = f.password_field :password_confirmation, id: 'password_confirmation'
      = f.label :password_confirmation, 'Confirmation', for: 'password_confirmation'

  .row
    .input-field.col.s6
      = render 'shared/remember_me.slim', form: '/register'
    .input-field.col.s6
      = f.button :submit, class: "btn waves-effect waves-light" do
        = content_tag(:span, new_user ? "Create Profile" : "Update Profile")

app/views/users/avatar.slim
= render 'shared/header', title: 'Avatar Upload'

= form_for(@user, url: update_avatar_user_path, html: {class: 'directUpload'}) do |f|
  = hidden_field_tag 'uploads'

  canvas#myCanvas

  ul#avatar-form
    .btn
      li
        #avatar
          = f.file_field :avatar_url
        = f.label :avatar_url, "Photo", class: 'btn file-btn'

      li
        button.btn.btn-success type='button' Upload

    .btn
      li
        = submit_tag "Update profile", class: 'btn btn-primary'
      -if !@user.avatar_url.include?('avatar-placeholder.png')
        li
          = link_to "Delete avatar", delete_avatar_user_path(current_user), class: 'btn btn-danger',
          method: :delete, data: { confirm: 'Are You sure?' }

= render 'avatar'

app/views/users/edit.slim
= render 'form'

app/views/users/new.slim
= render 'form'

app/views/users/show.slim
- @show_msgs ||= false
= render 'shared/header', title: @user.username

.card-panel.teal.lighten-5.z-depth-3
  .row
    -if logged_in? && @user != current_user
      .right
        = link_to new_message_path do
          i.material-icons
            | drafts
    .col.s6
      = image_tag @user.avatar_url, class: 'responsive-img'
    .col.s6
      em> Username:
      = @user.username
      br
      em> Email verified:
      = @user.verified == true ? 'Yes' : 'No'

span.activity
  = @user.username
  | 's Activity
.row
  .col.s12
    ul.tabs#user-activity
      li.tab.col.s3
        = link_to "Questions (#{@user.questions.size})", "#questions"
      li.tab.col.s3
        = link_to "Comments (#{@user.comments.size})", "#comments"
      - if @show_msgs
        li.tab.col.s3
          = link_to "Recieved Messages (#{@user.recieved_messages.size})", "#recieved"
        li.tab.col.s3
          = link_to "Sent Messages (#{@user.sent_messages.size})", "#sent"
    #questions.col.s12
      = render @user.questions
      = render 'shared/pagination', page_count: Question::PER_PAGE, url: user_path(@user)
    #comments.col.s12
      = render @user.comments
      = render "shared/pagination", page_count: Comment::PER_PAGE, url: user_path(@user), other_params: "#comments"
    #recieved.col.s12
      = render @user.recieved_messages
      = render 'shared/pagination', page_count: Message::PER_PAGE, url: user_path(@user), other_params: "#recieved"
    #sent.col.s12
      = render @user.sent_messages
      = render 'shared/pagination', page_count: Message::PER_PAGE, url: user_path(@user), other_params: "#sent"