config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  post '/search' => 'application#search'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :categories, except: :destroy do
    member do
      post 'sub'
      post 'unsub'
    end

    resources :questions, only: [:create, :show, :index], shallow: true do
      post 'vote', on: :member

      resources :comments, only: [:create] do
        member do
          post 'vote'
          post 'best_answer'
        end
      end
    end
  end

  get '/register' => 'users#new'
  resources :users, except: [:destroy] do

    member do
      resources :messages, only: [:new, :create]
      get 'avatar'
      patch 'update_avatar'
      delete 'delete_avatar'
    end
  end

  resources :email_verifications, only: :edit

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Searchable
  PER_PAGE = 10

  validates :name, presence: true, length: {minimum: 3}
  validates :description, presence: true, length: {minimum: 5}

  has_many :questions
  has_many :user_categories
  has_many :users, through: :user_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create, :sub, :unsub]
  before_action :find_category, only: [:show, :sub, :unsub]

  def index
    if logged_in?
      user_subs
      @categories = Category.where.not(id: user_subs).limit(Category::PER_PAGE).offset(params[:offset])
    else
      @categories = Category.limit(Category::PER_PAGE).offset(params[:offset])
    end
    @pages = (Category.all.size.to_f / Category::PER_PAGE).ceil
  end

  def show
    @question = Question.new
    @questions = @category.questions.limit(Question::PER_PAGE).offset(params[:offset])
    @pages = (@category.questions.size.to_f / Question::PER_PAGE).ceil
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(params.require(:category).permit(:name, :description))

    if @category.save
      flash[:success] = 'Your category has been created.'
      redirect_to @category
    else
      render :new
    end
  end

  def sub
    if !current_user.subs.include? @category
      current_user.subs << @category
      respond_to do |format|
        format.html { redirect_to :back }
        format.json { render json: @category }
      end
    end
  end

  def unsub
    if current_user.subs.include? @category
      current_user.subs.delete @category
      respond_to do |format|
        format.html {redirect_to :back}
        format.json { render json: @category }
      end
    end
  end

private

  def user_subs
    @user_subs ||= Category.where(id: current_user.subs.ids)
  end

  def find_category
    @category = Category.find params[:id]
  end
end

app/views/categories/_category.slim
.row
  .col.s12
    = link_to category.name, category
    span.info<
      = pluralize category.questions.count, "Question"
    span.right-align
      - if logged_in?
        - if current_user.subs.include? category
          = form_tag "/categories/#{category.id}/unsub", class: 'star'
            = link_to "#" do
              i.material-icons>
                | remove_circle 
        - else
          = form_tag "/categories/#{category.id}/sub", class: "sub star"
            = link_to "#" do
              i.material-icons>
                | add_circle
.row
  .col.s12.truncate
    = category.description
.divider
            

app/views/categories/_subscribe.slim
ul.card-panel.teal.lighten-4.z-depth-1
  h4 Category details
  hr.header
  li
    ' Created:
    = time_ago_in_words category.created_at
    |  ago
  li
    ' Questions:
    = category.questions.count
  - if logged_in?
    li
      - if current_user.subs.include? category
          = form_tag "/categories/#{category.id}/unsub", class: 'star'
            = link_to '#' do
              i.material-icons>
                | remove_circle
              | Unsubscribe
      -else
          = form_tag "/categories/#{category.id}/sub", class: 'sub star'
            = link_to '#' do
              i.material-icons>
                | add_circle
              | Subscribe

app/views/categories/index.slim
= render 'shared/header', title: 'Categories'

- if logged_in? && (params[:offset].nil? || params[:offset] == '0')
  = render @user_subs

= render @categories

= render 'shared/pagination', page_count: Category::PER_PAGE, url: categories_path

app/views/categories/new.slim
h3 New Category
= form_for @category do |f|
  .row
    .input-field.col.s12
      = f.text_field :name
      = f.label :name, for: "name"

  .row
    .input-field.col.s12
      = f.text_area :description, class: 'materialize-textarea'
      = f.label :description, for: "description"

  = f.button :submit, class: 'btn waves-effect waves-light' do
    = content_tag(:span, "Create")

app/views/categories/show.slim
= render 'shared/header', title: @category.name

.row
  .col.s3
    = render 'subscribe', category: @category
    - if logged_in? && current_user.verified
      = render 'questions/form'

  .col.s9
    = render @questions

- if @questions.any?
  = render 'shared/pagination', page_count: Question::PER_PAGE, url: category_path(@category)