config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  post '/search' => 'application#search'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :categories, except: :destroy do
    member do
      post 'sub'
      post 'unsub'
    end

    resources :questions, only: [:create, :show, :index], shallow: true do
      post 'vote', on: :member

      resources :comments, only: [:create] do
        member do
          post 'vote'
          post 'best_answer'
        end
      end
    end
  end

  get '/register' => 'users#new'
  resources :users, except: [:destroy] do

    member do
      resources :messages, only: [:new, :create]
      get 'avatar'
      patch 'update_avatar'
      delete 'delete_avatar'
    end
  end

  resources :email_verifications, only: :edit

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_msgs.slim
-if flash.keys.any?
  - flash.each do |type, msg|
    .card-panel class="#{type == 'success' ? 'green lighten-1' : 'red lighten-1'}"
      div id="#{type}" =msg

app/views/layouts/_navbar.slim
nav
  ul.right.hide-on-med-and-down
    li
      = link_to 'DiY', root_path
    - if logged_in? and current_user.unread_messages.any?
      li= link_to user_path(current_user, tab: 'recieved') do
        i.glyphicon.glyphicon-envelope
  ul#slide-out.side-nav.fixed
    li= link_to 'Categories', categories_path
    - if logged_in?
      li= link_to 'New Category', new_category_path
      a.dropdown-button.btn href="#" data-activates='dropdown1'
        = current_user.username
      ul#dropdown1.dropdown-content
        li
          = link_to current_user do
            i.material-icons>
              | perm_identity
            | Account
        li= link_to edit_user_path(current_user) do
          i.material-icons>
            | perm_data_setting
          | Edit Profile
        li= link_to avatar_user_path(current_user) do
          i.material-icons>
            | face
          | Avatar
        li.divider
          li= link_to logout_path, method: :delete do
            i.material-icons>
              | exit_to_app
            | Logout
    - else
      li= link_to "Create Profile", register_path
      li= link_to "Login", login_path

  a.button-collapse href="#" data-activates="slide-out"
    i.mdi-navigation-menu

app/views/layouts/_search.slim
=form_tag '/search', class: 'navbar-form navbar-right' do
  .input-group
    =text_field_tag :search_term, nil, placeholder: 'Search term', class: 'form-control'
    span.input-group-btn
      =submit_tag 'Search', class: 'btn btn-default'

app/views/layouts/application.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"

    title Diy
    = stylesheet_link_tag 'application', "https://fonts.googleapis.com/icon?family=Material+Icons", media: 'all', 'data-turbolinks' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/navbar'
    .container
      = render 'layouts/msgs'
      = yield